/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testjapp;
import testjapp.models.*;
import org.springframework.boot.*;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Person p = new Person();
        p.setAge(56);
        p.setFirstName("Bob");
        p.setLastName("Villa");
        p.setAge(56);

        System.out.println(new App().getGreeting());
        System.out.println(p.getFirstName());
        System.out.println(p.getLastName());

        // all you need is this below:
        SpringApplication.run(App.class, args);
    }
}
