/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testjapp.models;
import org.springframework.data.annotation.Id;

public class Person {
    @Id private String id;

    private String firstName;
    private String lastName;
    private int age;
    private String notes;
    private String ssn;

    public String getSsn() {
      return ssn;
    }

    public void setSsn(String ssn) {
      this.ssn = ssn;
    }


    public String getFirstName() {
      return firstName;
    }

    public void setFirstName(String firstName) {
      this.firstName= firstName;
    }

    public String getLastName() {
      return lastName;
    }

    public void setLastName(String lastName) {
      this.lastName= lastName;
    }

    public int getAge() {
      return age;
    }
    public void setAge(int age) {
      this.age=age;
    }
    public String getNotes() {
      return notes;
    }

    public void setNotes(String notes) {
      this.notes = notes;
    }


}
